export const SET_GAMES = 'SET_GAMES';
export const SET_MEETINGS = 'SET_MEETINGS';
export const SET_USER_MEETINGS = 'SET_USER_MEETINGS';

export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_FILTERS = 'SET_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const MEETING_REQUESTED = 'REGISTER_REQUESTED';
export const MEETING_SUCCESS = 'REGISTER_SUCCESS';
export const MEETING_FAIL = 'REGISTER_FAIL';

export const JOIN_REQUESTED = 'JOIN_REQUESTED';
export const JOIN_SUCCESS = 'JOIN_SUCCESS';
export const JOIN_FAIL = 'JOIN_FAIL';